openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
tags:
  - name: cyclists
    description: Operaciones con ciclistas
  - name: teams
    description: Operaciones con equipos
servers:
  - url: 'https://api.example.com'
paths:
  /cyclists:
    get:
      tags:
        - cyclists
      summary: Devuelve los ciclistas registrados.
      description: |   
        Devuelve un listado con los ciclistas solicitados dependiento de los filtros aplicados
      
        Se puede filtrar a través de cualquier de los filtros indicados name, specialty, birthplace incluso ambos al mismo tiempo
          - **name**: Filtra por nombre
          - **specialty**: Filtra por especialidad
          - **birthplace**: Filtra por lugar de nacimiento
      parameters:
        - name: name
          in: query
          description: Filtro para nombre del ciclista
          required: false
          schema:
            type: string
        - name: specialty
          in: query
          description: Filtro para especialidad del ciclista
          required: false
          schema:
            type: string
        - name: birthplace
          in: query
          description: Filtro para especialidad del ciclista
          required: false
          schema:
             type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CyclistOutDto'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /cyclists/{cyclistId}:
    get:
      tags:
        - cyclists
      summary: Detalle de un ciclista
      description: Devuelve los detalles de un ciclista específico
      parameters:
        - name: cyclistId
          in: path
          description: Identificador del ciclista
          required: true
          schema:
            type: number
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CyclistOutDto'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - cyclists
      summary: Elimina un ciclista
      description: Dar de baja el ciclista cuyo id se pasa como parámetro
      parameters:
        - name: cyclistId
          in: path
          description: Identificador del ciclista
          required: true
          schema:
            type: number
            format: int64
      responses:
        '204':
          description: No content
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - cyclists
      summary: Modifica un ciclista
      description: Permite modificar algunos detalles de un coche
      parameters:
        - name: cyclistId
          in: path
          description: Identificador del ciclista
          required: true
          schema:
            type: number
            format: int64
      requestBody:
        description: Nuevos detalles del ciclista
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CyclistInDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CyclistOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /teams/{teamId}/cyclists:
    post:
      tags:
        - cyclists
        - teams
      summary: Registra un ciclista
      description: Dar de alta un nuevo ciclista según la información facilitada
      parameters:
        - name: teamId
          in: path
          description: Identificador del equipo al que pertenece el ciclista
          required: true
          schema:
            type: number
            format: int64
      requestBody:
        description: Detalles del nuevo ciclista
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CyclistRegistrationDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CyclistOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /teams:
    get:
      tags:
        - teams
      summary: Devuelve el listado de equipos
      description: |
        Devuelve un listado con los equipos registrados dependiento de los filtros aplicados

        Se puede filtrar a través de cualquier de los filtros indicados name, specialty, birthplace incluso ambos al mismo tiempo
          - **name**: Filtra por nombre
          - **specialty**: Filtra por especialidad
          - **birthplace**: Filtra por lugar de nacimiento
      parameters:
        - name: name
          in: query
          description: Filtro para nombre del ciclista
          required: false
          schema:
            type: string
        - name: specialty
          in: query
          description: Filtro para especialidad del ciclista
          required: false
          schema:
            type: string
        - name: birthplace
          in: query
          description: Filtro para especialidad del ciclista
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamOutDto'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - teams
      summary: Registra un equipo
      description: Dar de alta un nuevo equipo según la información facilitada
      requestBody:
        description: Detallos del nuevo equipo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /teams/{teamId}:
    delete:
      tags:
        - teams
      summary: Elimina un equipo
      description: Dar de baja el equipo cuyo id se pasa como parámetro
      parameters:
        - name: teamId
          in: path
          description: Identificador del equipo
          required: true
          schema:
            type: number
            format: int64
      responses:
        '204':
          description: No content
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - teams
      summary: Modifica un equipo
      description: Permite modificar algunos detalles de un equipo
      parameters:
        - name: teamId
          in: path
          description: Identificador del equipo
          required: true
          schema:
            type: number
            format: int64
      requestBody:
        description: Nuevos detalles del ciclista
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamInDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CyclistInDto:
      type: object
      properties:
        name:
          type: string
          description: Nombre del ciclista
          example: Pogaçar
        specialty:
          type: string
          description: Especialidad del ciclista
          example: Escalador
        birthplace:
          type: string
          description: Lugar de nacimiento del ciclista
          example: Denmark
        titles:
          type: number
          format: int64
          description: Titulos ganador por el ciclista
          example: 10
        birthdate:
          type: string
          format: date
          description: Fecha de nacimiento del ciclista
          example: 2000-12-30
    CyclistRegistrationDto:
      type: object
      properties:
        name:
          type: string
          description: Nombre del ciclista
          example: Pogaçar
        specialty:
          type: string
          description: Especialidad del ciclista
          example: Escalador
        birthplace:
          type: string
          description: Lugar de nacimiento del ciclista
          example: Denmark
        titles:
          type: number
          format: int64
          description: Titulos ganados por el ciclista
          example: 10
        weight:
          type: number
          format: float
          description: Peso del ciclista
          example: 62
        birthdate:
          type: string
          format: date
          description: Fecha de nacimiento del ciclista
          example: 2000-12-30
        isLeader:
          type: boolean
          description: Está activo o no el ciclista
          example: true
    CyclistOutDto:
      type: object
      properties:
        id:
          type: number
          format: int64
          description: El identificador del ciclista
          example: 1
        name:
          type: string
          description: Nombre del ciclista
          example: Pogaçar
        specialty:
          type: string
          description: Especialidad del ciclista
          example: Escalador
        birthplace:
          type: string
          description: Lugar de nacimiento del ciclista
          example: Denmark
        titles:
          type: number
          format: int64
          description: Titulos ganador por el ciclista
          example: 10
        weight:
          type: number
          format: float
          description: Peso del ciclista
          example: 62
        birthdate:
          type: string
          format: date
          description: Fecha de nacimiento del ciclista
          example: 2000-12-30
        isLeader:
          type: boolean
          description: Está activo o no el ciclista
          example: true
        teamId:
          type: number
          format: int64
          description: identificador del equipo al que pertenece
          example: 98
    Team:
      type: object
      properties:
        name:
          type: string
          description: Nombre del equipo
        email:
          type: string
          description: Email del equipo
        country:
          type: string
          description: Procedencia del equipo
        budget:
          type: number
          format: int64
          description: presupuesto del equipo
        fundationDate:
          type: string
          format: date
          description: Fecha de fundación del equipo
      example:
        name: UAE
        email: uae@gmail.com
        country: Emirates
        budget: 240
        fundationDate: 2015-12-30
    TeamInDto:
      allOf:
        - $ref: '#/components/schemas/Team'
    TeamOutDto:
      allOf:
      - $ref: '#/components/schemas/Team'
      - type: object
        properties:
          id:
            type: number
            format: int64
            description: Identificador único del equipo
            example: 65
      example:
        id: 95
        name: UAE
        email: uae@gmail.com
        country: Emirates
        budget: 240
        fundationDate: 2015/12/30
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Código de error
        message:
          type: string
          description: Descripción del error
    BadRequest:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        errorMessages:
          type: array
          items:
            $ref: '#/components/schemas/ErrorMessage'
      example:
        code: 400
        message: Bad Request
    ErrorMessage:
      type: object
      properties:
        fieldName:
          type: string
          description: Campo donde está el error
          example: model
        message:
          type: string
          description: Mensaje de error asociado al campo
          example: El dato es obligatorio
    NotFound:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 404
        message: Not Found
    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 500
        message: Internal Server Error
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'






